Update export-asset.yml

diff --git a/.github/workflows/export-asset.yml b/.github/workflows/export-asset.yml
--- a/.github/workflows/export-asset.yml
+++ b/.github/workflows/export-asset.yml
@@ -42,19 +42,35 @@ jobs:
         working-directory: AssetStudioModCli
         run: |
           chmod +x ./AssetStudioModCLI
-          EXPORT_DIR="${{ github.workspace }}/export"
+          EXPORT_DIR="${{ github.workspace }}/new-export"
           mkdir -p "$EXPORT_DIR"
           ./AssetStudioModCLI "${{ github.workspace }}/${{ env.PERSISTENT_STORE }}" -t "tex2d" --image-format "webp" -o "$EXPORT_DIR"
-          ./AssetStudioModCLI "${{ github.workspace }}/${{ env.INSTALL_RESOURCE }}" -t "tex2d" --image-format "webp" -o "$EXPORT_DIR"
+          # ./AssetStudioModCLI "${{ github.workspace }}/${{ env.INSTALL_RESOURCE }}" -t "tex2d" --image-format "webp" -o "$EXPORT_DIR"
         shell: bash
 
-      - name: Show exported files
+      - name: Sync new-export to export
         run: |
-          echo "=== export/ contents ==="
-          find export -type f -printf '%s\t%p\n' | sort -k2 | awk '{ printf "%10d  %s\n", $1, $2 }'
-          echo "=== total size ==="
-          du -sh export
-          echo "=== file count ==="
-          find export -type f | wc -l
+          mkdir -p export
+          rsync -av "new-export/" "export/"
+        shell: bash
+
+      - name: Commit and push export/
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add export
+
+          VERSION_JSON="${{ env.MANIFEST_VERSION_FILE }}"
+          if [ ! -f "$VERSION_JSON" ]; then
+            echo "manifest version.json not found. skipping commit"
+            exit 1
+          fi
+          GAME_VER=$(jq -r ".\"CN\".game_ver" "$VERSION_JSON")
+          if git diff --cached --quiet; then
+            echo "No changes to commit"
+          else
+            git commit -m "chore: update $GAME_VER"
+            git push
+          fi
         shell: bash
       
